spring:
  application:
    name: llm-low-code-platform
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/llm_low_code
    username: root
    password: 123456
  profiles:
    active: local
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      ttl: 3600
      user: root
  session:
    store-type: redis
    timeout: 2592000

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: org.n1vnhil.llm.lowcode.dev.platform.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# langchain4j
langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen3-coder-plus
      log-requests: true
      log-responses: true
      max-tokens: 8192
      response-format: json_object
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen3-coder-plus
      max-tokens: 8192
      log-requests: true
      log-responses: true
